// components/page-margin.tsx
import { cn } from '@/lib/utils';
import type { ReactNode } from 'react';

export function PageMargin({
  children,
  className = '',
}: {
  children: ReactNode;
  className?: string;
}) {
  return (
    <div
      className={cn(
        'mx-auto max-w-7xl px-3 sm:px-4 md:px-6 lg:px-8',
        className,
      )}
    >
      {children}
    </div>
  );
}

// src/lib/components/PageMargin.svelte
<script lang="ts">
import { resolveClass } from '$lib/utils/resolve-class';
let className = '';
export { className as class };
export let verticalMargin = false;
</script>

<div
  class={resolveClass(
    "mx-auto max-w-7xl px-3 sm:px-4 md:px-6 lg:px-8",
    verticalMargin && "py-8 lg:py-16",
    className,
  )}
>
  <slot />
</div>
